### ISSUE TITLE
.NET in docker ok?

### ISSUE THREAD

**Issue by 1tylermitchell** [Xgames123/PrimitierMultiplayerMod#2]
hi, thanks so much for sharing this, I'm excited to try it. Does it still work in docker? Do I need to download and install a dotnet docker option? If it was supposed to I guess it failed but I didn't notice.

I get error:
```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'PrimS.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

**Comment by Xgames123** [comment]
I think the docker file was broken
Its best to just install it on the host machine without using docker

**Comment by 1tylermitchell** [comment]
Thanks for quick response. I will do without docker, but wondering if I got the right version of dotnet runtime, which versions are you using? I'm running this on Linux and getting a warning only I think:

```
$ ./PrimitierServer
You must install or update .NET to run this application.

App: /home/tyler/src/primitier2/PrimitierServer
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '5.0.0' (x64)
.NET location: /snap/dotnet-runtime-70/12

The following frameworks were found:
  7.0.2 at [/snap/dotnet-runtime-70/12/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64
```

**Comment by Xgames123** [comment]
You need to install .Net 5.0
at the bottom of the error it gives you the exact download link I think
[https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64](https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=ubuntu.20.04-x64)

**Comment by 1tylermitchell** [comment]
Ok, that's what I've done. I must have an issue with my environment then.
